name: Lint Python

on: [push, pull_request]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "."
          src: "./"
          jupyter: true
      - uses: psf/black@stable

  lint-diff:
    if: failure()
    needs: lint-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  add-lint:
    if: failure()
    needs: [lint-diff]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "."
          src: "./"
          jupyter: true
